# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_recepta', models.CharField(max_length=120)),
                ('postopek_recepta', models.TextField()),
                ('sestavine_recepta', models.TextField()),
                ('datum_objave', models.DateField(auto_now_add=True)),
                ('slika_recepta', models.ImageField(upload_to='images')),
            ],
        ),
    ]
