# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRecipes', '0003_recept_glavna_sestavina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='glavna_sestavina',
        ),
    ]
